<?php
/**
 * @file
 * This module is the "Golden Contact Rock, Paper, Scissors" functions.
 *
 * **-DATE-**
 *
 */
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 * Which path of the site we're using to display help
 * @param arg
 * Array that holds the current path as returned from arg() function
 */
function pagelinks_help($path, $arg) {
    switch ($path) {
        case "admin/help#pagelinks":
            return '<p>'.t("This is the Pagelinks Module").'</p>';
            break;
    }
}
/**
 * Implements hook_block_info().
 */
function pagelinks_block_info() {
    $blocks['pagelinks'] = array(
        'info' => t('The Page Links block'), //The name that will appear in the block list.
        'cache' => DRUPAL_CACHE_PER_ROLE //Default
    );
    return $blocks;
}
/**
 * Implements hook_block_view().
 */
function pagelinks_block_view($delta = '') {
    $block['content'] = "" ;
    switch($delta){
        case 'pagelinks_oop':
            $block['subject'] = t('Some data from an OO Class');
            if(user_access('access content')){
                require_once(dirname(__FILE__)."/Libraries/HelloLib.php");
                $hello = new HelloLib() ;
                $word = $hello->sayHelloForMe() ;
                $block['content'] = $word; }
            break ;
        case 'pagelinks_procedural':
            $block['subject'] = t('A simple bit of data from a variable_get');
            if(user_access('access content')){
                $word = variable_get("hello_world") ;
                $block['content'] = $word; }
            break ;
    }
    return $block;
}